apiVersion: v1
kind: Pod
metadata:
  name: shell
  namespace: default
spec:
  containers:
  - name: shell
    image: debian:bookworm
    command:
      - sleep
      - "infinity"
    imagePullPolicy: IfNotPresent
  restartPolicy: Always